apiVersion: apps/v1
kind: Deployment
metadata:
  name: sypmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sypmd
  template:
    metadata:
      labels:
        app: sypmd
    spec:
      containers:
      - image: okteto.dev/sypmd:latest
        name: sypmd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "azmovies.net"
        - name: Vless_UUID
          value: "2333c208-831f-437c-ba2f-90105e7c47fb"
        - name: Vless_Path
          value: "/vlessertrj"
        - name: Vmess_UUID
          value: "2333c208-831f-437c-ba2f-90105e7c47fb"
        - name: Vmess_Path
          value: "/vmesssdhfj"
        - name: Share_Path
          value: "$Share_Path"
