apiVersion: apps/v1
kind: Deployment
metadata:
  name: afdbhd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afdbhd
  template:
    metadata:
      labels:
        app: afdbhd
    spec:
      containers:
      - image: okteto.dev/afdbhd:latest
        name: afdbhd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vecteezy.com"
        - name: Vless_UUID
          value: "17dd08a9-8e52-437f-9df8-6972bec7fb38"
        - name: Vless_Path
          value: "/vlessytj"
        - name: Vmess_UUID
          value: "17dd08a9-8e52-437f-9df8-6972bec7fb38"
        - name: Vmess_Path
          value: "/vmessseree"
        - name: Share_Path
          value: "$Share_Path"
