apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbxyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbxyt
  template:
    metadata:
      labels:
        app: mbxyt
    spec:
      containers:
      - image: okteto.dev/mbxyt:latest
        name: mbxyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "okmusi.com"
        - name: Vless_UUID
          value: "720bfe3a-b7fc-4c0a-ab6c-b6db94433985"
        - name: Vless_Path
          value: "/vlessqwty"
        - name: Vmess_UUID
          value: "720bfe3a-b7fc-4c0a-ab6c-b6db94433985"
        - name: Vmess_Path
          value: "/vmesswtri"
        - name: Share_Path
          value: "$Share_Path"
