apiVersion: apps/v1
kind: Deployment
metadata:
  name: wqfavn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wqfavn
  template:
    metadata:
      labels:
        app: wqfavn
    spec:
      containers:
      - image: okteto.dev/wqfavn:latest
        name: wqfavn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "okmusi.com"
        - name: Vless_UUID
          value: "0d2a7d9d-4093-48c4-8d1b-6c06760dc187"
        - name: Vless_Path
          value: "/vlesseopp"
        - name: Vmess_UUID
          value: "0d2a7d9d-4093-48c4-8d1b-6c06760dc187"
        - name: Vmess_Path
          value: "/vmessvbbz"
        - name: Share_Path
          value: "$Share_Path"
